const english = {
    protect: 'protect',
    ourElders: 'our elders',
    protectOurElders: 'Protect Our Elders',
    home: 'Home',
    aboutUs: 'About Us',
    getInvolved: 'Get Involved',
    volunteers: 'Volunteers',
    piyc: 'Protection In Your City',
    feedback: 'Feedback',
    donations: 'Donations',
    donate: 'Donate',
    makeADonation: 'Make A Donation',
    sponsors: 'Sponsors',
    media: 'Media',
    contactUs: 'Contact Us',
    more: 'More',
    resources: 'Resources',
    requestAVolunteer: 'Request A Volunteer',
    becomeAVolunteer: 'Become A Volunteer',
    adminLogin: 'Admin Login',
    copyright: 'Copyright',
    getInTouch: 'Get in touch with us',
    feelFree: 'Feel free to leave us a message and we will get back to you as soon as we can:',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    sendMessage: 'Send Message',
}

export default english