const simplified_chinese = {
    protect: '守卫',
    ourElders: '我们的长辈',
    protectOurElders: '守卫我们的长辈',
    home: '主页',
    aboutUs: '关于我们',
    getInvolved: '加入',
    volunteers: '成为义工',
    piyc: '城市守卫',
    feedback: '意见反馈',
    donations: '捐款',
    donate: '捐款',
    makeADonation: '完成一次捐款',
    sponsors: '赞助商',
    media: '媒体',
    contactUs: '联系我们',
    more: '更多',
    resources: '资源',
    requestAVolunteer: '申请义工',
    becomeAVolunteer: '成为义工',
    adminLogin: '管理员登陆',
    copyright: '版权',
    getInTouch: '请与我们联系',
    feelFree: '请随时给我们留言，我们将尽快与您联系:',
    name: '姓名',
    email: '邮箱',
    message: '信息',
    sendMessage: '发送消息',
    generalVol: '普通志愿者申请',
    allChap: '所有的陪护员都必须完成这个申请',
    clickHere: '点击此处',
    specificVol: '特殊志愿者申请',
    volDisp: '派遣志愿者（远程):',
    dispDesc: `如果您擅长组织与管理，我们很乐意将您安排至帮助长辈们寻求陪护员的配对工作中。我们要求您必须可以流利的使用粤语，普通话，或者越南话。`,
    comOutreach: '社区外展:',
    comDesc: `当我们共同努力时，我们的社区会变得更加强大。扩展本地业务，并且建立一个我们的长辈们可以信赖的关系网络。`,
    copywriting: '文案（远程):',
    copywritingDesc: `我们才刚刚起步， 所以我们需要帮助以随时更新小区的动态。`,
    social: '社交媒体（远程):',
    socialDesc: `通过各种新途径来帮助我们传播我们的思想到需要我们帮助的社区里。`,
    admin: '管理:',
    adminDesc: `在幕后有很多的东西需要处理，如果您觉得您的技能和想法可以帮助到我们，请联系我们。`,
    covidSub: `提交COVID-19的检测`,
    covidDesc: `为了我们的志愿者和我们所服务的社区的安全，我们要求所有进行现场工作的志愿者接受COVID-19测试，并在完成入职培训后提交您检测结果的屏幕截图/照片。`,
}


export default simplified_chinese