const simplified_chinese = {
    protect: '守卫',
    ourElders: '我们的长辈',
    protectOurElders: '守卫我们的长辈',
    home: '主页',
    aboutUs: '关于我们',
    getInvolved: '加入',
    volunteers: '成为义工',
    piyc: '城市守卫',
    feedback: '意见反馈',
    donations: '捐款',
    donate: '捐款',
    makeADonation: '完成一次捐款',
    sponsors: '赞助商',
    media: '媒体',
    contactUs: '联系我们',
    more: '更多',
    resources: '资源',
    requestAVolunteer: '申请义工',
    becomeAVolunteer: '成为义工',
    adminLogin: '管理员登陆',
    copyright: '版权',
    getInTouch: '请与我们联系',
    feelFree: '请随时给我们留言，我们将尽快与您联系:',
    name: '姓名',
    email: '邮箱',
    message: '信息',
    sendMessage: '发送消息',
    generalVol: '普通志愿者申请',
    allChap: '所有的陪护员都必须完成这个申请',
    clickHere: '点击此处',
    specificVol: '特殊志愿者申请',
    volDisp: '派遣志愿者（远程):',
    dispDesc: `如果您擅长组织与管理，我们很乐意将您安排至帮助长辈们寻求陪护员的配对工作中。我们要求您必须可以流利的使用粤语，普通话，或者越南话。`,
    comOutreach: '社区外展:',
    comDesc: `当我们共同努力时，我们的社区会变得更加强大。扩展本地业务，并且建立一个我们的长辈们可以信赖的关系网络。`,
    copywriting: '文案（远程):',
    copywritingDesc: `我们才刚刚起步， 所以我们需要帮助以随时更新小区的动态。`,
    social: '社交媒体（远程):',
    socialDesc: `通过各种新途径来帮助我们传播我们的思想到需要我们帮助的社区里。`,
    admin: '管理:',
    adminDesc: `在幕后有很多的东西需要处理，如果您觉得您的技能和想法可以帮助到我们，请联系我们。`,
    covidSub: `提交COVID-19的检测`,
    covidDesc: `为了我们的志愿者和我们所服务的社区的安全，我们要求所有进行现场工作的志愿者接受COVID-19测试，并在完成入职培训后提交您检测结果的屏幕截图/照片。`,
    softwareEngineer: "軟件工程師",
    aboutUsBio:
        "在2020的10月26日，7个有抱负的程序员开启了能改变他们一生的旅程。从最初的只知道如何循环一组数组，我们怀揣着我们的梦想在应用学院（App Academy) 里最杰出的团体中拥有了我们的一席之地。我们开辟了一条通往未知的新道路并决定征服软体工程世界。我们刻苦学习，我们大声欢笑，我们有时也会哭泣，而且我们开发了一些软件以模因的形式来纪念我们难忘的时刻。最重要的是，我们建立起了一生坚固的友谊。在疫情期间，对于亚太裔社区的针对暴力事件使我们的集体受到了极大的影响。当你使用暴力对任何一个人， 特别是对我们社区中最弱势和最受尊敬的群体，不管你是来自什么人种，什么文化族群， 或者其他特别的身份，都应该受到道德上的谴责。在这个项目中，我们致力于站出来作为一个榜样和应用我们所学到的技术来达成这个目的。我们希望将这个项目捐赠给任何有意愿和有能力承担的个人或者组织。如果您对这个项目有兴趣，请随时联系我们。还有不管何时何地，请散发出我们的爱而不是仇恨。",
    feedback: '反馈',
    stillGrowing: `我们还在扩展中！如果您是使用我们服务的社区成员或志愿者，我们很想听听您对我们的反馈以及如何改善我们的服务和行动。`,
    incidentReport: '事件报告',
    somethingDisturbing: '如果您是一位志愿者，在轮班期间经历或目睹了一些麻烦事，请在下面提交事件报告。',
    areThereElders: '在您的周围有需要看护的长辈吗？',
    wantToHelp: `我们希望对您社区的安全给与帮助！如果您希望我们扩大我们的工作范围并在您自己的所在地区启动一个新的保护项目，请填写以下表格，我们将尽快与您联系！`,
    inquire: 'I请在此处咨询',
    interestedSponsor: 'Interested In Becoming a Sponsor?',
    sponsorInfo: 'We are actively seeking new sponsors and partnerships. Please contact us if you are interested in contributing to our mission!',
    interestedDonate: 'Donations',
    donationInfo: 'Unfortunately, we are unable to accept donations at this time. Please check back in the near future, as we are rapidly growing and your generous contributions help us continue our mission.',

};
export default simplified_chinese;
