const traditional_chinese = {
    protect: '守衛',
    ourElders: '我們的長輩',
    protectOurElders: '守衛我們的長輩',
    home: '主頁',
    aboutUs: '關於我們',
    getInvolved: '加入',
    volunteers: '成為義工',
    piyc: '城市守衛',
    feedback: '意見反饋',
    donations: '捐款',
    donate: '捐款',
    makeADonation: '完成一次捐款',
    sponsors: '贊助商',
    media: '媒體',
    contactUs: '關於我們',
    more: '更多',
    resources: '資源',
    requestAVolunteer: '申請義工',
    becomeAVolunteer: '成為義工',
    adminLogin: '管理員登入',
    copyright: '版權',
    getInTouch: '請與我們聯繫',
    feelFree: '請隨時給我們留言，我們將盡快與您聯繫:',
    name: '姓名',
    email: '電子郵箱',
    message: '信息',
    sendMessage: '發送消息',
    generalVol: '普通志願者申請',
    allChap: '所有的陪護員都必須完成這個申請',
    clickHere: '點擊此處',
    specificVol: '特殊志願者申請',
    volDisp: '志願者派遣（遠程):',
    dispDesc: `如果您需要組織工作，我們很樂意為您提供幫助，幫助他們將志願者的日程安排與要求陪護者的老年人相匹配。必須能說流利的廣東話，普通話或越南語。`,
    comOutreach: '社區外展:',
    comDesc: `當我們共同努力時，我們的社區會變得更加強大。擴展本地業務，並且建立一個我們的長輩們可以信賴的關係網絡。`,
    copywriting: '文案（遠程):',
    copywritingDesc: `我們才剛剛起步， 所以我們需要幫助以隨時更新小區的動態。`,
    social: '社交媒體（遠程):',
    socialDesc: `通過各種新途徑來幫助我們傳播我們的思想到需要我們幫助的社區裡。`,
    admin: '管理:',
    adminDesc: `在幕後有很多的東西需要處理，如果您覺得您的技能和想法可以幫助到我們，請聯繫我們。`,
    covidSub: `提交COVID-19的檢測`,
    covidDesc: `為了我們的志願者和我們所服務的社區的安全，我們要求所有進行現場工作的志願者接受COVID-19測試，並在完成入職培訓後提交您檢測結果的屏幕截圖/照片。`,

}


export default traditional_chinese;