const traditional_chinese = {
    protect: '守衛',
    ourElders: '我們的長輩',
    protectOurElders: '守衛我們的長輩',
    home: '主頁',
    aboutUs: '關於我們',
    getInvolved: '加入',
    volunteers: '成為義工',
    piyc: '城市守衛',
    feedback: '意見反饋',
    donations: '捐款',
    donate: '捐款',
    makeADonation: '完成一次捐款',
    sponsors: '贊助商',
    media: '媒體',
    contactUs: '關於我們',
    more: '更多',
    resources: '資源',
    requestAVolunteer: '申請義工',
    becomeAVolunteer: '成為義工',
    adminLogin: '管理員登入',
    copyright: '版權',
    getInTouch: '請與我們聯繫',
    feelFree: '請隨時給我們留言，我們將盡快與您聯繫:',
    name: '姓名',
    email: '電子郵箱',
    message: '信息',
    sendMessage: '發送消息',
    generalVol: '普通志願者申請',
    allChap: '所有的陪護員都必須完成這個申請',
    clickHere: '點擊此處',
    specificVol: '特殊志願者申請',
    volDisp: '志願者派遣（遠程):',
    dispDesc: `如果您需要組織工作，我們很樂意為您提供幫助，幫助他們將志願者的日程安排與要求陪護者的老年人相匹配。必須能說流利的廣東話，普通話或越南語。`,
    comOutreach: '社區外展:',
    comDesc: `當我們共同努力時，我們的社區會變得更加強大。擴展本地業務，並且建立一個我們的長輩們可以信賴的關係網絡。`,
    copywriting: '文案（遠程):',
    copywritingDesc: `我們才剛剛起步， 所以我們需要幫助以隨時更新小區的動態。`,
    social: '社交媒體（遠程):',
    socialDesc: `通過各種新途徑來幫助我們傳播我們的思想到需要我們幫助的社區裡。`,
    admin: '管理:',
    adminDesc: `在幕後有很多的東西需要處理，如果您覺得您的技能和想法可以幫助到我們，請聯繫我們。`,
    covidSub: `提交COVID-19的檢測`,
    covidDesc: `為了我們的志願者和我們所服務的社區的安全，我們要求所有進行現場工作的志願者接受COVID-19測試，並在完成入職培訓後提交您檢測結果的屏幕截圖/照片。`,
    softwareEngineer: "軟件工程師",
    aboutUsBio: "在2020的10月26日，7個有抱負的程序員開啟了能改變他們一生的旅程。從最初的只知道如何循環一組數組，我們怀揣著我們的夢想在應用學院（App Academy) 裡最傑出的團體中擁有了我們的一席之地。我們開闢了一條通往未知的新道路並決定征服軟體工程世界。我們刻苦學習，我們大聲歡笑，我們有時也會哭泣，而且我們開發了一些軟件以模因的形式來紀念我們難忘的時刻。最重要的是，我們建立起了一生堅固的友誼。在疫情期間，對於亞太裔社區的針對暴力事件使我們的集體受到了極大的影響。當你使用暴力對任何一個人， 特別是對我們社區中最弱勢和最受尊敬的群體，不管你是來自什麼人種，什麼文化族群， 或者其他特別的身份，都應該受到道德上的譴責。在這個項目中，我們致力於站出來作為一個榜樣和應用我們所學到的技術來達成這個目的。我們希望將這個項目捐贈給任何有意願和有能力承擔的個人或者組織。如果您對這個項目有興趣，請隨時聯繫我們。還有不管何時何地，請散發出我們的愛而不是仇恨。",
    feedback: '反饋',
    stillGrowing: `我們還在擴展中！如果您是使用我們服務的社區成員或志願者，我們很想听聽您對我們的反饋以及如何改善我們的服務和行動。`,
    incidentReport: '事件報告',
    somethingDisturbing: '如果您是一位志願者，在輪班期間經歷或目睹了一些麻煩事，請在下面提交事件報告。',
    areThereElders: '在您的周圍有需要看護的長輩嗎？',
    wantToHelp: `我們希望對您社區的安全給與幫助！如果您希望我們擴大我們的工作範圍並在您自己的所在地區啟動一個新的保護項目，請填寫以下表格，我們將盡快與您聯繫！`,
    inquire: '請在此處諮詢',
    interestedSponsor: 'Interested In Becoming a Sponsor?',
    sponsorInfo: 'We are actively seeking new sponsors and partnerships. Please contact us if you are interested in contributing to our mission!',
    interestedDonate: 'Donations',
    donationInfo: 'Unfortunately, we are unable to accept donations at this time. Please check back in the near future, as we are rapidly growing and your generous contributions help us continue our mission.',
}


export default traditional_chinese;