const vietnamese = {
    protect: 'protect',
    ourElders: 'our elders',
    protectOurElders: 'Protect Our Elders',
    home: 'Home',
    aboutUs: 'About Us',
    getInvolved: 'Get Involved',
    volunteers: 'Volunteers',
    piyc: 'Protection In Your City',
    feedback: 'Feedback',
    donations: 'Donations',
    donate: 'Donate',
    makeADonation: 'Make A Donation',
    sponsors: 'Sponsors',
    media: 'Media',
    contactUs: 'Contact Us',
    more: 'More',
    resources: 'Resources',
    requestAVolunteer: 'Request A Volunteer',
    becomeAVolunteer: 'Become A Volunteer',
    adminLogin: 'Admin Login',
    copyright: 'Copyright',
    getInTouch: 'Get in touch with us',
    feelFree: 'Feel free to leave us a message and we will get back to you as soon as we can:',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    sendMessage: 'Send Message',
    generalVol: 'General Volunteer Application',
    allChap: 'All chaperones must fill out this application.',
    clickHere: 'Click Here',
    specificVol: 'Specific Volunteer Role Application',
    volDisp: 'Volunteer Dispatch (remote):',
    dispDesc: `If organization is your thing, we would love your help matching volunteer's schedules with seniors requesting a chaperone.Must be fluent in Cantonese, Mandarin, or Vietnamese.`,
    comOutreach: 'Community Outreach:',
    comDesc: `Communities are stronger when we work together. Reach out to local business' and help build out a network our seniors can rely on.`,
    copywriting: 'Copywriting (remote):',
    copywritingDesc: `We're just getting started, and we need help keeping the community updated on what's going on.`,
    social: 'Social Media (remote):',
    socialDesc: `Help spread the word and think through new avenues to reach target communities in need of assistance.`,
    admin: 'Admin:',
    adminDesc: `There's a lot to be done behind the scenes so reach out with your skillset and ideas on how you can apply them with us.`,
    covidSub: `COVID-19 Test Submission`,
    covidDesc: `For the safety of our volunteers and the community we are serving, we are asking that ALL volunteers doing in-person work to get tested for COVID-19 and to submit a screenshot/photo of your results after completing an onboarding session.`,
    softwareEngineer: "Software Engineer",
    aboutUsBio:
        "On October 26, 2020, seven aspiring developers set out on a journey that would change their lives forever. Equipped only with knowledge of how to iterate through an array and a dream, we took our places in App Academy's most illustrious cohort, and forged a path through the unknown, determined to conquer the world of software engineering. We learned, we laughed, we sometimes cried and developed applications to commemorate our pain in the form of memes. Most importantly, we crafted bonds of friendship and camaraderie that would last a lifetime. We collectively were, and still are, greatly affected by the rise of targeted violence against the AAPI community during the pandemic. Violence against anyone, especially the most vulnerable and revered members of our community, irrespective of their race, ethnicity, or other identifying characteristics, is both morally repugnant and reprehensible. With this project, we aim to take a stand and employ our development skills for good. We hope to donate this application to any person or organization with the desire and means to assume responsibility for what we've built. If this is something you might be interested in please do not hesitate to contact us. Until then, spread love not hate.",
    feedback: 'Feedback',
    stillGrowing: `We're still growing! If you are a volunteer or a community member who has used our service, we would love to hear your thoughts and feedback on what we are doing well, and how we can improve our service.`,
    incidentReport: 'Incident Report',
    somethingDisturbing: 'If you are a volunteer who has experienced or witnessed something disturbing during your shift, please file an incident report below.',
    areThereElders: 'Are There Elders That Need Protection In Your Area?',
    wantToHelp: `We want to help you keep your community safe! If you are hoping 
                to expand our efforts and start a new Protection project in your 
                own area, please fill out the form below and we will get back to 
                you soon!`,
    inquire: 'Inquire Here',
    interestedSponsor: 'Interested In Becoming a Sponsor?',
    sponsorInfo: 'We are actively seeking new sponsors and partnerships. Please contact us if you are interested in contributing to our mission!',
    interestedDonate: 'Donations',
    donationInfo: 'Unfortunately, we are unable to accept your donations at this time. Please check back in the near future, as we are rapidly growing and your generous contributions help us to continue our mission.',
};

export default vietnamese;